# Generated by Django 5.2.11 on 2026-08-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtítulo')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('image', models.URLField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png', help_text='Cole a URL da imagem de capa do post.', max_length=500, verbose_name='Imagem de capa')),
                ('content', models.TextField(help_text='Conteúdo principal do artigo.', verbose_name='Conteúdo')),
                ('author', models.CharField(blank=True, default='Produtos Nordeste', max_length=150, verbose_name='Autor')),
                ('is_published', models.BooleanField(default=False, help_text='Define se o post está visível no blog.', verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['title'], name='blog_post_title_e1c6f7_idx'), models.Index(fields=['slug'], name='blog_post_slug_cdb902_idx'), models.Index(fields=['is_published'], name='blog_post_is_publ_96cac2_idx'), models.Index(fields=['published_at'], name='blog_post_publish_698bc0_idx')],
            },
        ),
    ]
