# Generated by Django 5.2.11 on 2026-08-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Exponere', max_length=150, verbose_name='Autor'),
        ),
    ]
