# Generated by Django 5.2.11 on 2026-04-21 15:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Nome do cupom')),
                ('code', models.CharField(db_index=True, max_length=30, verbose_name='Código do cupom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite total de usos')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False)),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_coupons', to='catalog.catalog')),
            ],
        ),
        migrations.CreateModel(
            name='CouponFirstBuy',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupon.coupon')),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto percentual')),
                ('min_purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo da compra')),
            ],
            options={
                'verbose_name': 'Cupom Primeira Compra',
                'verbose_name_plural': 'Cupons Primeira Compra',
                'ordering': ['-updated_at'],
            },
            bases=('coupon.coupon',),
        ),
        migrations.CreateModel(
            name='CouponFixedValue',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupon.coupon')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do desconto')),
                ('min_purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo da compra')),
            ],
            options={
                'verbose_name': 'Cupom com Valor Fixo',
                'verbose_name_plural': 'Cupons com Valores Fixos',
                'ordering': ['-updated_at'],
            },
            bases=('coupon.coupon',),
        ),
        migrations.CreateModel(
            name='CouponPercentValue',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupon.coupon')),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto percentual')),
                ('min_purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo da compra')),
                ('max_discount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto máximo')),
            ],
            options={
                'verbose_name': 'Cupom com Valor Percentual',
                'verbose_name_plural': 'Cupons com Valores Percentuais',
                'ordering': ['-updated_at'],
            },
            bases=('coupon.coupon',),
        ),
        migrations.CreateModel(
            name='CouponProgressive',
            fields=[
                ('coupon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coupon.coupon')),
                ('min_purchase_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor mínimo da compra')),
                ('max_purchase_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor máximo da compra')),
                ('percent_discount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto percentual')),
            ],
            options={
                'verbose_name': 'Cupom Progressivo',
                'verbose_name_plural': 'Cupons Progressivos',
                'ordering': ['-updated_at'],
            },
            bases=('coupon.coupon',),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='coupon.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='customer.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
