# Generated by Django 5.2.11 on 2026-05-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
