# Generated by Django 5.2.11 on 2026-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_usage_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponfixedvalue',
            name='discount_value',
        ),
    ]
