# Generated by Django 5.2.11 on 2026-05-16 13:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_remove_couponfixedvalue_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponfixedvalue',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor do desconto'),
            preserve_default=False,
        ),
    ]
