# Generated by Django 5.2.11 on 2026-05-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_couponfixedvalue_discount_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de início'),
        ),
    ]
