# Generated by Django 5.2.11 on 2026-04-30 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('order', 'Pedido'), ('payment', 'Pagamento'), ('system', 'Sistema'), ('marketing', 'Marketing'), ('alert', 'Alerta')], default='system', max_length=50, verbose_name='Tipo de notificação')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='URL de ação')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Dados adicionais')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.catalog', verbose_name='Catálogo')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_543da6_idx'), models.Index(fields=['catalog'], name='notificatio_catalog_f2a38a_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_17d351_idx')],
            },
        ),
    ]
