# Generated by Django 5.2.11 on 2026-05-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('order', 'Pedido'), ('payment', 'Pagamento'), ('system', 'Sistema'), ('alert', 'Alerta')], default='system', max_length=50, verbose_name='Tipo de notificação'),
        ),
    ]
