# Generated by Django 5.2.11 on 2026-05-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('order', 'Pedido'), ('alert', 'Alerta')], default='alert', max_length=50, verbose_name='Tipo de notificação'),
        ),
    ]
