# Generated by Django 5.2.11 on 2026-05-11 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_name'),
        ('notification', '0003_alter_notification_type_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.catalog', verbose_name='Catálogo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('order', 'Pedido'), ('system', 'Sistema'), ('alert', 'Alerta')], default='system', max_length=50, verbose_name='Tipo de notificação'),
        ),
    ]
