services:
  backend:
    build: .
    container_name: exponere_backend
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "8000"

    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

    networks:
      - exponere

  celery:
    build: .
    container_name: exponere_celery
    command: celery -A core worker -l info

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - exponere

  celery_beat:
    build: .
    container_name: exponere_celery_beat
    command: celery -A core beat -l info

    env_file:
      - .env

    restart: unless-stopped

    networks:
      - exponere

  nginx:
    image: nginx:alpine
    container_name: exponere_nginx

    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

      - static_volume:/app/staticfiles
      - media_volume:/app/media

      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

    networks:
      - exponere

  certbot:
    image: certbot/certbot
    container_name: exponere_certbot

    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot

    entrypoint: >
      sh -c "trap exit TERM;
      while :;
      do
        certbot renew;
        sleep 12h;
      done"

networks:
  exponere:

volumes:
  static_volume:
  media_volume:
  certbot_conf:
  certbot_www: