services:

  backend:

    build: ./backend
    container_name: exponere_api
    ports:

      - "8000:8000"

    restart: always

    environment:

      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}

      GOOGLE_OAUTH_CALLBACK_URL: ${GOOGLE_OAUTH_CALLBACK_URL}
      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}

      SECRET_KEY: ${SECRET_KEY}

      STRIPE_TEST_SECRET_KEY: ${STRIPE_TEST_SECRET_KEY}
      STRIPE_TEST_PUBLIC_KEY: ${STRIPE_TEST_PUBLIC_KEY}
      STRIPE_TEST_WEBHOOK_SECRET: ${STRIPE_TEST_WEBHOOK_SECRET}

      STRIPE_PROD_SECRET_KEY: ${STRIPE_PROD_SECRET_KEY}
      STRIPE_PROD_PUBLIC_KEY: ${STRIPE_PROD_PUBLIC_KEY}
      STRIPE_PROD_WEBHOOK_SECRET: ${STRIPE_PROD_WEBHOOK_SECRET}

      STRIPE_LOCAL_DOMAIN_WEBHOOK: ${STRIPE_LOCAL_DOMAIN_WEBHOOK}
      STRIPE_PROD_DOMAIN_WEBHOOK: ${STRIPE_PROD_DOMAIN_WEBHOOK}

      STRIPE_LOCAL_PLAN_PREMIUM: ${STRIPE_LOCAL_PLAN_PREMIUM}
      STRIPE_LOCAL_PLAN_PREMIUM_2: ${STRIPE_LOCAL_PLAN_PREMIUM_2}

      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      
      DEBUG: ${DEBUG}

    networks:

      - private_network
      - public_network