# Generated by Django 5.2.11 on 2026-02-25 00:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('api_custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF (XXX.XXX.XXX-XX) ou CNPJ (XX.XXX.XXX/XXXX-XX) válido', regex='^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2})$')], verbose_name='CPF ou CNPJ'),
        ),
        migrations.AddField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite um número válido com DDD (ex: +5511999999999)', regex='^\\+?55\\d{10,11}$')], verbose_name='WhatsApp'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
