# Generated by Django 5.2.11 on 2026-03-15 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0002_profile_address_profile_cpf_cnpj_profile_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_of_use_is_ready',
            field=models.BooleanField(default=False, verbose_name='Termos de uso foi lido'),
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='api_custom__email_f4ec8b_idx'), models.Index(fields=['token'], name='api_custom__token_3ad85b_idx')],
            },
        ),
    ]
