# Generated by Django 5.2.11 on 2026-04-10 01:23

import api.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Digite um CPF ou CNPJ válido (alfanumérico permitido).', regex='^[A-Za-z0-9./-]{11,18}$'), api.utils.validate_no_repeated_chars], verbose_name='CPF ou CNPJ'),
        ),
    ]
