# Generated by Django 5.2.11 on 2026-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0003_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CPF ou CNPJ'),
        ),
    ]
