# Generated by Django 5.2.11 on 2026-03-19 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_city'),
        ('api_custom_auth', '0003_userprofile_terms_of_use_is_ready_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_affiliate',
            field=models.BooleanField(default=False, verbose_name='É afiliado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Endereço'),
        ),
    ]
