# Generated by Django 5.2.11 on 2026-04-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0004_alter_profile_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
