# Generated by Django 5.2.11 on 2026-04-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0006_alter_passwordreset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('reader', 'Leitor')], default='admin', max_length=10),
        ),
    ]
