# Generated by Django 5.2.11 on 2026-04-24 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_custom_auth', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Digite um número válido com DDD (ex: +5511999999999)', regex='^\\+?55\\d{10,11}$')], verbose_name='WhatsApp'),
        ),
    ]
