# Generated by Django 5.2.11 on 2026-07-15 00:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMarketingLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('file_url', models.URLField(max_length=1000, verbose_name='URL do material')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Início da campanha')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim da campanha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campanha de Marketing',
                'verbose_name_plural': 'Campanhas de Marketing',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MarketingLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um número válido com DDD (ex: +5511999999999)', regex='^\\+?55\\d{10,11}$')], verbose_name='WhatsApp')),
                ('monthly_revenue', models.CharField(blank=True, choices=[('UP_TO_5K', 'Até R$ 5 mil/mês'), ('FROM_5K_TO_10K', 'De R$ 5 mil a R$ 10 mil/mês'), ('FROM_10K_TO_30K', 'De R$ 10 mil a R$ 30 mil/mês'), ('FROM_30K_TO_50K', 'De R$ 30 mil a R$ 50 mil/mês'), ('FROM_50K_TO_100K', 'De R$ 50 mil a R$ 100 mil/mês'), ('FROM_100K_TO_300K', 'De R$ 100 mil a R$ 300 mil/mês'), ('ABOVE_300K', 'Acima de R$ 300 mil/mês')], max_length=30, verbose_name='Faturamento mensal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_marketing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing_launch.campaignmarketinglaunch')),
            ],
            options={
                'verbose_name': 'Lead de Marketing',
                'verbose_name_plural': 'Leads de Marketing',
            },
        ),
    ]
