# Generated by Django 5.2.11 on 2026-07-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_launch', '0002_alter_marketinglaunch_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglaunch',
            name='monthly_revenue',
            field=models.CharField(choices=[('UP_TO_5K', 'Até R$ 5 mil/mês'), ('FROM_5K_TO_10K', 'De R$ 5 mil a R$ 10 mil/mês'), ('FROM_10K_TO_30K', 'De R$ 10 mil a R$ 30 mil/mês'), ('FROM_30K_TO_50K', 'De R$ 30 mil a R$ 50 mil/mês'), ('FROM_50K_TO_100K', 'De R$ 50 mil a R$ 100 mil/mês'), ('FROM_100K_TO_300K', 'De R$ 100 mil a R$ 300 mil/mês'), ('ABOVE_300K', 'Acima de R$ 300 mil/mês')], max_length=30, verbose_name='Faturamento mensal'),
        ),
    ]
