# Generated by Django 5.2.11 on 2026-07-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_launch', '0003_alter_marketinglaunch_monthly_revenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglaunch',
            name='whatsapp',
            field=models.CharField(max_length=20, verbose_name='WhatsApp'),
        ),
    ]
