# Generated by Django 5.2.11 on 2026-07-16 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_launch', '0004_alter_marketinglaunch_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketinglaunch',
            name='campaign_marketing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='marketing_launch.campaignmarketinglaunch'),
        ),
    ]
