# Generated by Django 5.2.11 on 2026-03-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, help_text='Número identificador da nota fiscal.', max_length=50, null=True, verbose_name='Número da nota fiscal')),
                ('access_key', models.CharField(blank=True, db_index=True, max_length=44, null=True, unique=True, verbose_name='Chave de acesso')),
                ('file_url', models.URLField(blank=True, help_text='URL do PDF ou XML da nota fiscal.', null=True, verbose_name='Arquivo da nota fiscal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.OneToOneField(help_text='Pedido relacionado a esta nota fiscal.', on_delete=django.db.models.deletion.CASCADE, related_name='nf', to='order.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='nf_nf_created_80fd21_idx'), models.Index(fields=['number'], name='nf_nf_number_6bcfb8_idx')],
            },
        ),
    ]
