# Generated by Django 5.2.11 on 2026-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
