# Generated by Django 5.2.11 on 2026-05-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plugin_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
