# Generated by Django 5.2.11 on 2026-03-19 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_address_city_remove_address_state'),
        ('api_custom_auth', '0004_userprofile_is_affiliate_alter_profile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
