# Generated by Django 5.2.11 on 2026-05-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_plugin_is_active'),
        ('catalog', '0003_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugin',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog', verbose_name='Catalogo'),
        ),
    ]
