# Generated by Django 5.2.11 on 2026-07-21 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
        ('api', '0004_alter_plugin_catalog'),
    ]

    operations = [
    ]
