# Generated by Django 5.2.11 on 2026-05-03 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_integration',
            field=models.BooleanField(default=False, verbose_name='vem de uma integração?'),
        ),
    ]
