# Generated by Django 5.2.11 on 2026-05-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('customer', '0002_alter_customer_address_alter_customer_is_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address_customer', to='address.address', verbose_name='Endereço'),
        ),
    ]
