# Generated by Django 5.2.11 on 2026-05-18 00:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_plugin_is_active'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GA4',
            fields=[
                ('plugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.plugin')),
                ('measurement_id', models.CharField(blank=True, help_text='Ex: G-ABC123XYZ9', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Informe um Measurement ID válido. Ex: G-ABC123XYZ9', regex='^G-[A-Z0-9]{8,12}$')], verbose_name='Measurement ID')),
                ('property_id', models.CharField(blank=True, help_text='Ex: 123456789', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Property ID deve conter apenas números.', regex='^\\d+$')], verbose_name='Property ID')),
            ],
            options={
                'verbose_name': 'Google Analytics 4',
                'verbose_name_plural': 'Google Analytics 4',
            },
            bases=('api.plugin',),
        ),
        migrations.CreateModel(
            name='MetaPixel',
            fields=[
                ('plugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.plugin')),
                ('pixel_id', models.CharField(blank=True, help_text='Ex: 123456789012345', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Informe um Pixel ID válido contendo apenas números.', regex='^\\d{10,20}$')], verbose_name='Pixel ID')),
            ],
            options={
                'verbose_name': 'Meta Pixel',
                'verbose_name_plural': 'Meta Pixels',
            },
            bases=('api.plugin',),
        ),
        migrations.AlterModelOptions(
            name='tagmanager',
            options={'verbose_name': 'Google Tag Manager', 'verbose_name_plural': 'Google Tag Managers'},
        ),
        migrations.AddField(
            model_name='tagmanager',
            name='container_id',
            field=models.CharField(blank=True, help_text='Ex: GTM-ABC1234', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Informe um Container ID válido. Ex: GTM-ABC1234', regex='^GTM-[A-Z0-9]+$')], verbose_name='Container ID'),
        ),
    ]
