# Generated by Django 5.2.11 on 2026-04-30 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do plano (ex: Básico, Premium)', max_length=100, unique=True)),
                ('lookup_key_plan', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do plano', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor do plano em BRL', max_digits=10)),
                ('currency', models.CharField(default='BRL', help_text='Moeda do plano', max_length=10)),
                ('duration', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', help_text='Periodicidade do plano', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Se o plano está disponível para assinaturas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(help_text='ID do cliente no Stripe.', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(help_text='ID da sessão de checkout no Stripe.', max_length=255)),
                ('stripe_price_id', models.CharField(help_text='ID do preço do produto/assinatura no Stripe.', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID da assinatura no Stripe, se aplicável.', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID do Payment Intent no Stripe.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='pending', help_text='Status do pagamento.', max_length=20)),
                ('has_access', models.BooleanField(default=False, help_text='Indica se o usuário ganhou acesso ao produto/serviço.')),
                ('is_completed', models.BooleanField(default=False, help_text='Indica se o fluxo de checkout foi finalizado.')),
                ('plan_start_date', models.DateTimeField(blank=True, help_text='Data de início do plano.', null=True)),
                ('plan_end_date', models.DateTimeField(blank=True, help_text='Data de fim do plano, caso o usuário cancele.', null=True)),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da compra (em BRL).', max_digits=10, null=True)),
                ('currency', models.CharField(default='BRL', help_text='Moeda utilizada na transação.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.OneToOneField(help_text='O usuário que iniciou o checkout.', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan', verbose_name='Plano do Usuário')),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
