# Generated by Django 5.2.6 on 2025-09-18 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(help_text='ID do cliente no Stripe.', max_length=255)),
                ('stripe_checkout_session_id', models.CharField(help_text='ID da sessão de checkout no Stripe.', max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(help_text='ID do preço do produto/assinatura no Stripe.', max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='ID da assinatura no Stripe, se aplicável.', max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='ID do Payment Intent no Stripe.', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('canceled', 'Cancelado')], default='pending', help_text='Status do pagamento.', max_length=20)),
                ('has_access', models.BooleanField(default=False, help_text='Indica se o usuário ganhou acesso ao produto/serviço.')),
                ('is_completed', models.BooleanField(default=False, help_text='Indica se o fluxo de checkout foi finalizado.')),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, help_text='Valor total da compra (em BRL).', max_digits=10, null=True)),
                ('currency', models.CharField(default='BRL', help_text='Moeda utilizada na transação.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('user', models.ForeignKey(help_text='O usuário que iniciou o checkout.', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkout',
                'verbose_name_plural': 'Checkouts',
                'ordering': ['-created_at'],
            },
        ),
    ]
