# Generated by Django 5.2.11 on 2026-04-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsessionrecord',
            name='stripe_checkout_session_id',
            field=models.CharField(help_text='ID da sessão de checkout no Stripe.', max_length=255),
        ),
    ]
