# Generated by Django 5.2.6 on 2025-10-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='plan_end_date',
            field=models.DateTimeField(blank=True, help_text='Data de fim do plano, caso o usuário cancele.', null=True),
        ),
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, help_text='Data de início do plano.', null=True),
        ),
    ]
