# Generated by Django 5.2.6 on 2025-10-05 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_checkoutsessionrecord_plan_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do plano (ex: Básico, Premium)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição do plano', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Valor do plano em BRL', max_digits=10)),
                ('currency', models.CharField(default='BRL', help_text='Moeda do plano', max_length=10)),
                ('duration', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', help_text='Periodicidade do plano', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Se o plano está disponível para assinaturas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='checkoutsessionrecord',
            name='user',
            field=models.OneToOneField(help_text='O usuário que iniciou o checkout.', on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkoutsessionrecord',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan'),
        ),
    ]
