# Generated by Django 5.2.6 on 2025-10-05 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_plan_alter_checkoutsessionrecord_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='lookup_key_plan',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='checkoutsessionrecord',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.plan', verbose_name='Plano do Usuário'),
        ),
    ]
