# Generated by Django 5.2.11 on 2026-07-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Feedback'),
        ),
    ]
