# Generated by Django 5.2.11 on 2026-04-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AI', '0001_initial'),
        ('catalog', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyproduct',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog', verbose_name='Catalogo'),
        ),
        migrations.AddField(
            model_name='copyproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='product.product', verbose_name='Produto'),
        ),
        migrations.AddIndex(
            model_name='copyproduct',
            index=models.Index(fields=['product'], name='AI_copyprod_product_28c099_idx'),
        ),
        migrations.AddIndex(
            model_name='copyproduct',
            index=models.Index(fields=['created_at'], name='AI_copyprod_created_e30c05_idx'),
        ),
    ]
