# Generated by Django 5.2.11 on 2026-03-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=255, verbose_name='Código de rastreio')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_transit', 'Em trânsito'), ('out_for_delivery', 'Saiu para entrega'), ('delivered', 'Entregue'), ('failed', 'Falha na entrega'), ('returned', 'Devolvido')], default='pending', max_length=50, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição do status')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localização (ex: São Paulo - SP)')),
                ('raw_response', models.JSONField(blank=True, null=True, verbose_name='Resposta bruta da API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_statuses', to='order.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Status de entrega',
                'verbose_name_plural': 'Status de entregas',
                'ordering': ['-updated_at'],
            },
        ),
    ]
