# Generated by Django 5.2.11 on 2026-04-19 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscategory',
            options={'verbose_name': 'Categoria do Negócio', 'verbose_name_plural': 'Categorias dos Negócios'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category', verbose_name='Categoria'),
        ),
    ]
