# Generated by Django 5.2.11 on 2026-04-30 23:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade disponível')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade reservada')),
                ('min_quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade mínima')),
                ('max_quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade máxima')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de compra')),
                ('type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('RESERVE', 'Reserva'), ('RELEASE', 'Liberação')], max_length=10, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stock.stock', verbose_name='Estoque')),
            ],
            options={
                'verbose_name': 'Movimentação de estoque',
                'verbose_name_plural': 'Movimentações de estoque',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notified', models.BooleanField(default=False, help_text='Indica se o usuário já foi notificado sobre o estoque.', verbose_name='Já notificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Alerta de estoque',
                'verbose_name_plural': 'Alertas de estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'product'], name='stock_alert_email_f4ef72_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'product'), name='unique_email_product_alert')],
            },
        ),
    ]
