# Generated by Django 5.2.11 on 2026-04-03 19:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_subcategory'),
        ('stock', '0002_alter_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço de compra'),
        ),
        migrations.CreateModel(
            name='AlertProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('notified', models.BooleanField(default=False, help_text='Indica se o usuário já foi notificado sobre o estoque.', verbose_name='Já notificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Alerta de estoque',
                'verbose_name_plural': 'Alertas de estoque',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'product'], name='stock_alert_email_f4ef72_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'product'), name='unique_email_product_alert')],
            },
        ),
    ]
