# Generated by Django 5.2.11 on 2026-04-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='product.product')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key'], name='wishlist_wi_session_3ad878_idx'), models.Index(fields=['created_at'], name='wishlist_wi_created_7481f7_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'session_key'), name='unique_product_session_wishlist')],
            },
        ),
    ]
