# Generated by Django 5.2.11 on 2026-05-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wishlist',
            name='unique_product_session_wishlist',
        ),
    ]
