# Generated by Django 5.2.11 on 2026-04-16 00:01

import api.address.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='O CEP deve conter exatamente 8 números (sem hífen ou letras).', regex='^\\d{8}$'), api.address.utils.validate_no_repeated_digits], verbose_name='CEP'),
        ),
    ]
