# Generated by Django 5.2.11 on 2026-08-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='number',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
