# Generated by Django 5.2.11 on 2026-08-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_address_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número'),
        ),
    ]
