# Generated by Django 5.2.11 on 2026-04-30 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=155, null=True, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo por pedido para frete grátis')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço promocional')),
                ('promotion_is_active', models.BooleanField(default=True, verbose_name='Preço promocional está ativo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog', verbose_name='Catalogo')),
                ('category', models.ManyToManyField(blank=True, to='category.category', verbose_name='Categorias')),
                ('subcategory', models.ManyToManyField(blank=True, to='category.subcategory', verbose_name='Subcategorias')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png', max_length=500, verbose_name='Foto')),
                ('alt_text', models.TextField(blank=True, null=True, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Imagem de Anúncio',
                'verbose_name_plural': 'Imagens de Anúncios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductLogisticInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Peso')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Altura')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Largura')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento')),
                ('volume', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Volume')),
                ('unit_of_measure', models.CharField(blank=True, choices=[('unit', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro'), ('cm', 'Centímetro')], db_index=True, max_length=20, null=True, verbose_name='Unidade de medida')),
                ('packaging_type', models.CharField(blank=True, choices=[('box', 'Caixa'), ('bag', 'Saco'), ('pallet', 'Pallet'), ('bottle', 'Garrafa'), ('unit', 'Unidade'), ('other', 'Outro')], db_index=True, max_length=20, null=True, verbose_name='Tipo de embalagem')),
                ('quantity_per_box', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade por caixa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_info', to='product.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Informação p/ Logística do Produto',
                'verbose_name_plural': 'Informações p/ Logística dos Produtos',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog'], name='product_pro_catalog_a23c26_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='product_pro_title_07e491_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='product_pro_is_acti_9d034c_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['product'], name='product_ima_product_11eb72_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['created_at'], name='product_ima_created_5df723_idx'),
        ),
        migrations.AddIndex(
            model_name='productlogisticinfo',
            index=models.Index(fields=['product'], name='product_pro_product_680062_idx'),
        ),
        migrations.AddIndex(
            model_name='productlogisticinfo',
            index=models.Index(fields=['unit_of_measure'], name='product_pro_unit_of_0f6955_idx'),
        ),
        migrations.AddIndex(
            model_name='productlogisticinfo',
            index=models.Index(fields=['packaging_type'], name='product_pro_packagi_93cbed_idx'),
        ),
    ]
