# Generated by Django 5.2.11 on 2026-04-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(blank=True, to='category.subcategory', verbose_name='Categorias'),
        ),
    ]
