# Generated by Django 5.2.11 on 2026-05-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='Valor mínimo por pedido para frete grátis'),
        ),
    ]
