# Generated by Django 5.2.11 on 2026-04-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlogisticinfo',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistic_info', to='product.product', verbose_name='Produto'),
        ),
    ]
