# Generated by Django 5.2.11 on 2026-04-29 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productlogisticinfo_product'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='product_ima_is_main_4bfc35_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='is_main',
        ),
    ]
