# Generated by Django 5.2.11 on 2026-03-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Nome da empresa')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_img', models.URLField(blank=True, null=True, verbose_name='Logotipo da empresa')),
                ('banner_img', models.URLField(blank=True, null=True, verbose_name='Foto do banner')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo por pedido')),
                ('minimum_order_value_free_shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo por pedido para frete grátis')),
                ('about', models.TextField(default='Meu catálogo digital ; )')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Link da rede social')),
                ('social_name', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X/Twitter'), ('site', 'Site'), ('outro', 'Outro')], max_length=20, verbose_name='Rede social')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Abre às')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Fecha às')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado neste dia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['weekday', 'open_time'],
            },
        ),
    ]
