# Generated by Django 5.2.11 on 2026-04-21 15:17

import api.utils
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Nome da empresa')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('photo_img', models.URLField(blank=True, null=True, verbose_name='Logotipo da empresa')),
                ('banner_img', models.URLField(blank=True, null=True, verbose_name='Foto do banner')),
                ('minimum_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor mínimo por pedido')),
                ('minimum_order_value_free_shipping', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor mínimo por pedido para frete grátis')),
                ('about', models.TextField(default='Meu catálogo digital ; )')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='https://exponere.com.br', validators=[api.utils.validate_not_empty_url], verbose_name='Link da rede social')),
                ('social_name', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X/Twitter'), ('site', 'Site'), ('outro', 'Outro')], max_length=20, verbose_name='Rede social')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
