# Generated by Django 5.2.11 on 2026-03-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='Abre às')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='Fecha às')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Fechado neste dia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Horário de funcionamento',
                'verbose_name_plural': 'Horários de funcionamento',
                'ordering': ['weekday', 'open_time'],
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='banner_img',
            field=models.URLField(blank=True, null=True, verbose_name='Foto do banner'),
        ),
    ]
