# Generated by Django 5.2.11 on 2026-05-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, default='catalogo', max_length=155, null=True, verbose_name='Nome da empresa'),
        ),
    ]
