# Generated by Django 5.2.11 on 2026-03-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_openinghours_catalog_banner_img'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.businesscategory', verbose_name='Categoria da Empresa'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo por pedido'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='minimum_order_value_free_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor mínimo por pedido para frete grátis'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Nome da empresa'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='photo_img',
            field=models.URLField(blank=True, null=True, verbose_name='Logotipo da empresa'),
        ),
        migrations.AddField(
            model_name='link',
            name='social_name',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X/Twitter'), ('site', 'Site'), ('outro', 'Outro')], max_length=20, verbose_name='Rede social'),
        ),
        migrations.AddField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link da rede social'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.catalog', verbose_name='Catalogo'),
        ),
        migrations.AddField(
            model_name='openinghours',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='catalog.catalog', verbose_name='Catálogo'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('catalog', 'weekday', 'open_time')},
        ),
    ]
