# Generated by Django 5.2.11 on 2026-04-18 14:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='minimum_order_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor mínimo por pedido'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='minimum_order_value_free_shipping',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor mínimo por pedido para frete grátis'),
        ),
    ]
