# Generated by Django 5.2.11 on 2026-04-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_minimum_order_value_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OpeningHours',
        ),
    ]
