# Generated by Django 5.2.11 on 2026-07-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='social_name',
            field=models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('x', 'X/Twitter'), ('whatsapp', 'WhatsApp'), ('site', 'Site'), ('outro', 'Outro')], max_length=20, verbose_name='Rede social'),
        ),
    ]
