# Generated by Django 5.2.11 on 2026-04-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(default='https://exponere.com.br', verbose_name='Link da rede social'),
        ),
    ]
