# Generated by Django 5.2.11 on 2026-04-19 14:07

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(default='https://exponere.com.br', validators=[api.utils.validate_not_empty_url], verbose_name='Link da rede social'),
        ),
    ]
