# Generated by Django 5.2.11 on 2026-07-15 00:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Digite um número válido com DDD (ex: +5511999999999)', regex='^\\+?55\\d{10,11}$')], verbose_name='WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email de Launch',
                'verbose_name_plural': 'Emails da Launch',
            },
        ),
    ]
