# Generated by Django 5.2.11 on 2026-07-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp'),
        ),
    ]
