name: Exponere API CICD

on: 
    push:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        env:

          API_KEY: ${{ secrets.API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
          GOOGLE_OAUTH_CALLBACK_URL: ${{ secrets.GOOGLE_OAUTH_CALLBACK_URL }}
          GOOGLE_OAUTH_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}
          GOOGLE_OAUTH_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH_CLIENT_SECRET }}

          SECRET_KEY: ${{ secrets.SECRET_KEY }}

          STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
          STRIPE_TEST_PUBLIC_KEY: ${{ secrets.STRIPE_TEST_PUBLIC_KEY }}
          STRIPE_TEST_WEBHOOK_SECRET: ${{ secrets.STRIPE_TEST_WEBHOOK_KEY }}

          STRIPE_PROD_SECRET_KEY: ${{ secrets.STRIPE_PROD_SECRET_KEY }}
          STRIPE_PROD_PUBLIC_KEY: ${{ secrets.STRIPE_PROD_PUBLIC_KEY }}
          STRIPE_PROD_WEBHOOK_SECRET: ${{ secrets.STRIPE_PROD_WEBHOOK_KEY }}

          STRIPE_LOCAL_DOMAIN_WEBHOOK: ${{ secrets.STRIPE_LOCAL_DOMAIN_WEBHOOK }}
          STRIPE_PROD_DOMAIN_WEHBOOK: ${{ secrets.STRIPE_PROD_DOMAIN_WEBHOOK }}

          STRIPE_LOCAL_PLAN_PREMIUM: ${{ secrets.STRIPE_LOCAL_PLAN_PREMIUM }}
          STRIPE_LOCAL_PLAN_PREMIUM_2: ${{ secrets.STRIPE_LOCAL_PLAN_PREMIUM_2 }}

          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_SENDER_DOMAIN: ${{ secrets.MAILGUN_SENDER_DOMAIN }}
          MAILGUN_WELCOME_EMAIL_TEMPLATE: ${{ secrets.MAILGUN_WELCOME_EMAIL_TEMPLATE }}
          MAILGUN_PASSWORD_RESET_EMAIL_TEMPLATE: ${{ secrets.MAILGUN_PASSWORD_RESET_EMAIL_TEMPLATE }}
          MAILGUN_CONFIRMATION_EMAIL_TEMPLATE: ${{ secrets.MAILGUN_CONFIRMATION_EMAIL_TEMPLATE }}
          MAILGUN_REMINDER_PRODUCT_EMAIL_TEMPLATE: ${{ secrets.MAILGUN_REMINDER_PRODUCT_EMAIL_TEMPLATE }}

          STRAPI_API_KEY: ${{ secrets.STRAPI_API_KEY }}
          STRAPI_ARTICLE_URL: ${{ secrets.STRAPI_ARTICLE_URL }}
          STRAPI_CATEGORY_URL: ${{ secrets.STRAPI_CATEGORY_URL }}

          PROPERTY_ID_GA4: ${{ secrets.PROPERTY_ID_GA4 }}

          GA4_CREDENTIALS: ${{ secrets.GA4_CREDENTIALS }}

          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

          CELERY_BROKER_URL_TEST: ${{ secrets.CELERY_BROKER_URL_TEST }}
          CELERY_RESULT_BACKEND_TEST: ${{ secrets.CELERY_RESULT_BACKEND_TEST }}

          CELERY_BROKER_URL_PROD: ${{ secrets.CELERY_BROKER_URL_PROD }}
          CELERY_RESULT_BACKEND_PROD: ${{ secrets.CELERY_RESULT_BACKEND_PROD }}

          MELHOR_ENVIO_CLIENT_ID: ${{ secrets.MELHOR_ENVIO_CLIENT_ID }}
          MELHOR_ENVIO_CLIENT_SECRET: ${{ secrets.MELHOR_ENVIO_CLIENT_SECRET }}
          MELHOR_ENVIO_ACCESS_TOKEN: ${{ secrets.MELHOR_ENVIO_ACCESS_TOKEN }}
          
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Set up Python v3.12
              uses: actions/setup-python@v3
              with:
                python-version: 3.12

            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run Tests
              run: |
                python manage.py test
    deploy:

        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Deploy to Vercel
              run: |
                vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm