# Generated by Django 5.2.11 on 2026-03-15 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='Palavra-chave')),
                ('slug', models.SlugField(blank=True, max_length=60, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='catalog.catalog', verbose_name='Catálogo')),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['keyword'],
                'indexes': [models.Index(fields=['keyword'], name='SEO_keyword_keyword_c1e8f6_idx'), models.Index(fields=['slug'], name='SEO_keyword_slug_e38640_idx')],
                'constraints': [models.UniqueConstraint(fields=('catalog', 'keyword'), name='unique_keyword_per_catalog')],
            },
        ),
    ]
