# Generated by Django 5.2.11 on 2026-03-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SEO', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='catalog.catalog', verbose_name='Catálogo'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['keyword'], name='SEO_keyword_keyword_c1e8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['slug'], name='SEO_keyword_slug_e38640_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('catalog', 'keyword'), name='unique_keyword_per_catalog'),
        ),
    ]
